CREATE TABLE IF NOT EXISTS BRANDS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRICES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CURR VARCHAR(3) NOT NULL,
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID)
);

INSERT INTO BRANDS (NAME) VALUES ('XXXX');

INSERT INTO PRICES (BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR)
SELECT BrandId,
       PARSEDATETIME(StartDate, 'yyyy-MM-dd-HH.mm.ss'),
       PARSEDATETIME(EndDate, 'yyyy-MM-dd-HH.mm.ss'),
       PriceList,
       ProductId,
       Priority,
       Price,
       Currency
FROM CSVREAD('classpath:prices.csv');
